# TCL File Generated by Component Editor 18.1
# Tue Jun 07 23:23:44 CEST 2022
# DO NOT MODIFY


# 
# adaptive_threshold "adaptive_threshold" v1.0
# Julien Burkhard 2022.06.07.23:23:44
# Accelerator for adaptive thresholding operation on image
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module adaptive_threshold
# 
set_module_property DESCRIPTION "Accelerator for adaptive thresholding operation on image"
set_module_property NAME adaptive_threshold
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Julien Burkhard"
set_module_property DISPLAY_NAME adaptive_threshold
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL adaptive_threshold_top_level
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file adaptive_threshold_top_level.vhd VHDL PATH ../hdl/adaptive_threshold_top_level.vhd TOP_LEVEL_FILE
add_fileset_file adaptive_threshold.vhd VHDL PATH ../hdl/adaptive_threshold.vhd
add_fileset_file avalon_slave.vhd VHDL PATH ../hdl/avalon_slave.vhd
add_fileset_file burst_reader.vhd VHDL PATH ../hdl/burst_reader.vhd
add_fileset_file burst_writer.vhd VHDL PATH ../hdl/burst_writer.vhd
add_fileset_file fifo_mult.vhd VHDL PATH ../hdl/fifo_mult.vhd
add_fileset_file finite_state_machine.vhd VHDL PATH ../hdl/finite_state_machine.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 avs_add address Input 2
add_interface_port avalon_slave_0 avs_wr write Input 1
add_interface_port avalon_slave_0 avs_rd read Input 1
add_interface_port avalon_slave_0 avs_wrdata writedata Input 32
add_interface_port avalon_slave_0 avs_rddata readdata Output 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point avalon_master_0
# 
add_interface avalon_master_0 avalon start
set_interface_property avalon_master_0 addressUnits SYMBOLS
set_interface_property avalon_master_0 associatedClock clock
set_interface_property avalon_master_0 associatedReset reset
set_interface_property avalon_master_0 bitsPerSymbol 8
set_interface_property avalon_master_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_master_0 burstcountUnits WORDS
set_interface_property avalon_master_0 doStreamReads false
set_interface_property avalon_master_0 doStreamWrites false
set_interface_property avalon_master_0 holdTime 0
set_interface_property avalon_master_0 linewrapBursts false
set_interface_property avalon_master_0 maximumPendingReadTransactions 0
set_interface_property avalon_master_0 maximumPendingWriteTransactions 0
set_interface_property avalon_master_0 readLatency 0
set_interface_property avalon_master_0 readWaitTime 1
set_interface_property avalon_master_0 setupTime 0
set_interface_property avalon_master_0 timingUnits Cycles
set_interface_property avalon_master_0 writeWaitTime 0
set_interface_property avalon_master_0 ENABLED true
set_interface_property avalon_master_0 EXPORT_OF ""
set_interface_property avalon_master_0 PORT_NAME_MAP ""
set_interface_property avalon_master_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_master_0 avm_add address Output 32
add_interface_port avalon_master_0 avm_wr write Output 1
add_interface_port avalon_master_0 avm_rd read Output 1
add_interface_port avalon_master_0 avm_wrdata writedata Output 32
add_interface_port avalon_master_0 avm_rddata readdata Input 32
add_interface_port avalon_master_0 avm_waitrequest waitrequest Input 1
add_interface_port avalon_master_0 avm_beginbursttransfer beginbursttransfer Output 1
add_interface_port avalon_master_0 avm_burstcount burstcount Output 7
add_interface_port avalon_master_0 avm_rddatavalid readdatavalid Input 1
add_interface_port avalon_master_0 avm_be byteenable Output 4


# 
# connection point fifo1
# 
add_interface fifo1 conduit end
set_interface_property fifo1 associatedClock clock
set_interface_property fifo1 associatedReset ""
set_interface_property fifo1 ENABLED true
set_interface_property fifo1 EXPORT_OF ""
set_interface_property fifo1 PORT_NAME_MAP ""
set_interface_property fifo1 CMSIS_SVD_VARIABLES ""
set_interface_property fifo1 SVD_ADDRESS_GROUP ""

add_interface_port fifo1 fifo1_data data Output 32
add_interface_port fifo1 fifo1_empty empty Input 1
add_interface_port fifo1 fifo1_q q Input 32
add_interface_port fifo1 fifo1_rdreq rdreq Output 1
add_interface_port fifo1 fifo1_sclr sclr Output 1
add_interface_port fifo1 fifo1_wrreq wrreq Output 1


# 
# connection point fifo2
# 
add_interface fifo2 conduit end
set_interface_property fifo2 associatedClock clock
set_interface_property fifo2 associatedReset ""
set_interface_property fifo2 ENABLED true
set_interface_property fifo2 EXPORT_OF ""
set_interface_property fifo2 PORT_NAME_MAP ""
set_interface_property fifo2 CMSIS_SVD_VARIABLES ""
set_interface_property fifo2 SVD_ADDRESS_GROUP ""

add_interface_port fifo2 fifo2_data data Output 32
add_interface_port fifo2 fifo2_empty empty Input 1
add_interface_port fifo2 fifo2_q q Input 32
add_interface_port fifo2 fifo2_rdreq rdreq Output 1
add_interface_port fifo2 fifo2_sclr sclr Output 1
add_interface_port fifo2 fifo2_wrreq wrreq Output 1


# 
# connection point fifo3
# 
add_interface fifo3 conduit end
set_interface_property fifo3 associatedClock clock
set_interface_property fifo3 associatedReset ""
set_interface_property fifo3 ENABLED true
set_interface_property fifo3 EXPORT_OF ""
set_interface_property fifo3 PORT_NAME_MAP ""
set_interface_property fifo3 CMSIS_SVD_VARIABLES ""
set_interface_property fifo3 SVD_ADDRESS_GROUP ""

add_interface_port fifo3 fifo3_data data Output 32
add_interface_port fifo3 fifo3_empty empty Input 1
add_interface_port fifo3 fifo3_q q Input 32
add_interface_port fifo3 fifo3_rdreq rdreq Output 1
add_interface_port fifo3 fifo3_sclr sclr Output 1
add_interface_port fifo3 fifo3_wrreq wrreq Output 1


# 
# connection point fifo4
# 
add_interface fifo4 conduit end
set_interface_property fifo4 associatedClock clock
set_interface_property fifo4 associatedReset ""
set_interface_property fifo4 ENABLED true
set_interface_property fifo4 EXPORT_OF ""
set_interface_property fifo4 PORT_NAME_MAP ""
set_interface_property fifo4 CMSIS_SVD_VARIABLES ""
set_interface_property fifo4 SVD_ADDRESS_GROUP ""

add_interface_port fifo4 fifo4_data data Output 32
add_interface_port fifo4 fifo4_empty empty Input 1
add_interface_port fifo4 fifo4_q q Input 32
add_interface_port fifo4 fifo4_rdreq rdreq Output 1
add_interface_port fifo4 fifo4_sclr sclr Output 1
add_interface_port fifo4 fifo4_wrreq wrreq Output 1


# 
# connection point fifolookahead
# 
add_interface fifolookahead conduit end
set_interface_property fifolookahead associatedClock clock
set_interface_property fifolookahead associatedReset ""
set_interface_property fifolookahead ENABLED true
set_interface_property fifolookahead EXPORT_OF ""
set_interface_property fifolookahead PORT_NAME_MAP ""
set_interface_property fifolookahead CMSIS_SVD_VARIABLES ""
set_interface_property fifolookahead SVD_ADDRESS_GROUP ""

add_interface_port fifolookahead ofifo_data data Output 32
add_interface_port fifolookahead ofifo_q q Input 32
add_interface_port fifolookahead ofifo_rdreq rdreq Output 1
add_interface_port fifolookahead ofifo_sclr sclr Output 1
add_interface_port fifolookahead ofifo_wrreq wrreq Output 1

