# TCL File Generated by Component Editor 18.1
# Mon Jun 06 14:56:31 CEST 2022
# DO NOT MODIFY


# 
# fifo_lookahead_comp "fifo_lookahead_comp" v1.0
#  2022.06.06.14:56:31
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module fifo_lookahead_comp
# 
set_module_property DESCRIPTION ""
set_module_property NAME fifo_lookahead_comp
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME fifo_lookahead_comp
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL fifolookahead
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file fifolookahead.vhd VHDL PATH fifolookahead.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point fifo
# 
add_interface fifo conduit end
set_interface_property fifo associatedClock clk
set_interface_property fifo associatedReset ""
set_interface_property fifo ENABLED true
set_interface_property fifo EXPORT_OF ""
set_interface_property fifo PORT_NAME_MAP ""
set_interface_property fifo CMSIS_SVD_VARIABLES ""
set_interface_property fifo SVD_ADDRESS_GROUP ""

add_interface_port fifo data data Input 32
add_interface_port fifo empty empty Output 1
add_interface_port fifo q q Output 32
add_interface_port fifo rdreq rdreq Input 1
add_interface_port fifo sclr sclr Input 1
add_interface_port fifo usedw usedw Output 7
add_interface_port fifo wrreq wrreq Input 1


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clock clk Input 1

